import store from "@/store";

export default [
    {
        path: "pay",
        name: "AdminPay",
        component: () => import("@/views/zhifu/zhifu"),
        meta: { authLogin: true },
    },

    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "xinwenfenlei",
        name: "AdminxinwenfenleiList",
        component: () => import("@/views/xinwenfenlei/list"),
        meta: { title: "新闻分类列表", authLogin: true },
    },
    {
        path: "xinwenfenleiadd",
        name: "AdminxinwenfenleiAdd",
        component: () => import("@/views/xinwenfenlei/add"),
        meta: { title: "添加新闻分类", authLogin: true },
    },
    {
        path: "xinwenfenleiupdt",
        name: "AdminxinwenfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/xinwenfenlei/updt"),
        meta: { title: "编辑新闻分类", authLogin: true },
    },
    {
        path: "xinwenxinxi",
        name: "AdminxinwenxinxiList",
        component: () => import("@/views/xinwenxinxi/list"),
        meta: { title: "新闻信息列表", authLogin: true },
    },
    {
        path: "xinwenxinxi_faburen",
        name: "AdminxinwenxinxiListfaburen",
        component: () => import("@/views/xinwenxinxi/list-faburen"),
        meta: { title: "新闻信息列表", authLogin: true },
    },
    {
        path: "xinwenxinxiadd",
        name: "AdminxinwenxinxiAdd",
        component: () => import("@/views/xinwenxinxi/add"),
        meta: { title: "添加新闻信息", authLogin: true },
    },
    {
        path: "xinwenxinxiupdt",
        name: "AdminxinwenxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/xinwenxinxi/updt"),
        meta: { title: "编辑新闻信息", authLogin: true },
    },
    {
        path: "liuyanban",
        name: "AdminliuyanbanList",
        component: () => import("@/views/liuyanban/list"),
        meta: { title: "留言板列表", authLogin: true },
    },
    {
        path: "liuyanban_liuyanren",
        name: "AdminliuyanbanListliuyanren",
        component: () => import("@/views/liuyanban/list-liuyanren"),
        meta: { title: "留言板列表", authLogin: true },
    },
    {
        path: "liuyanbanadd",
        name: "AdminliuyanbanAdd",
        component: () => import("@/views/liuyanban/add"),
        meta: { title: "添加留言板", authLogin: true },
    },
    {
        path: "liuyanbanupdt",
        name: "AdminliuyanbanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/liuyanban/updt"),
        meta: { title: "编辑留言板", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
    {
        path: "shoucang",
        name: "AdminshoucangList",
        component: () => import("@/views/shoucang/list"),
        meta: { title: "收藏列表", authLogin: true },
    },
    {
        path: "shoucang_username",
        name: "AdminshoucangListusername",
        component: () => import("@/views/shoucang/list-username"),
        meta: { title: "收藏列表", authLogin: true },
    },
    {
        path: "wxuser",
        name: "AdminwxuserList",
        component: () => import("@/views/wxuser/list"),
        meta: { title: "微信用户列表", authLogin: true },
    },
    {
        path: "wxuseradd",
        name: "AdminwxuserAdd",
        component: () => import("@/views/wxuser/add"),
        meta: { title: "添加微信用户", authLogin: true },
    },
    {
        path: "wxuserupdt",
        name: "AdminwxuserUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/wxuser/updt"),
        meta: { title: "编辑微信用户", authLogin: true },
    },
    {
        path: "wxuserdetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminwxuserDetail",
        component: () => import("@/views/wxuser/detail"),
        meta: { title: "微信用户详情", authLogin: true },
    },
    {
        path: "fenlei",
        name: "AdminfenleiList",
        component: () => import("@/views/fenlei/list"),
        meta: { title: "分类列表", authLogin: true },
    },
    {
        path: "fenleiadd",
        name: "AdminfenleiAdd",
        component: () => import("@/views/fenlei/add"),
        meta: { title: "添加分类", authLogin: true },
    },
    {
        path: "fenleiupdt",
        name: "AdminfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/fenlei/updt"),
        meta: { title: "编辑分类", authLogin: true },
    },
    {
        path: "jiaju",
        name: "AdminjiajuList",
        component: () => import("@/views/jiaju/list"),
        meta: { title: "家具列表", authLogin: true },
    },
    {
        path: "jiaju_tianjiaren",
        name: "AdminjiajuListtianjiaren",
        component: () => import("@/views/jiaju/list-tianjiaren"),
        meta: { title: "家具列表", authLogin: true },
    },
    {
        path: "jiajuadd",
        name: "AdminjiajuAdd",
        component: () => import("@/views/jiaju/add"),
        meta: { title: "添加家具", authLogin: true },
    },
    {
        path: "jiajuupdt",
        name: "AdminjiajuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jiaju/updt"),
        meta: { title: "编辑家具", authLogin: true },
    },
    {
        path: "jiajudetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjiajuDetail",
        component: () => import("@/views/jiaju/detail"),
        meta: { title: "家具详情", authLogin: true },
    },
    {
        path: "gouwuche",
        name: "AdmingouwucheList",
        component: () => import("@/views/gouwuche/list"),
        meta: { title: "购物车列表", authLogin: true },
    },
    {
        path: "gouwuche_goumairen",
        name: "AdmingouwucheListgoumairen",
        component: () => import("@/views/gouwuche/list-goumairen"),
        meta: { title: "购物车列表", authLogin: true },
    },
    {
        path: "dingdan",
        name: "AdmindingdanList",
        component: () => import("@/views/dingdan/list"),
        meta: { title: "订单列表", authLogin: true },
    },
    {
        path: "dingdan_xiadanren",
        name: "AdmindingdanListxiadanren",
        component: () => import("@/views/dingdan/list-xiadanren"),
        meta: { title: "订单列表", authLogin: true },
    },
    {
        path: "dingdanadd",
        name: "AdmindingdanAdd",
        component: () => import("@/views/dingdan/add"),
        meta: { title: "添加订单", authLogin: true },
    },
    {
        path: "dingdanupdt",
        name: "AdmindingdanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/dingdan/updt"),
        meta: { title: "编辑订单", authLogin: true },
    },
    {
        path: "dingdandetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmindingdanDetail",
        component: () => import("@/views/dingdan/detail"),
        meta: { title: "订单详情", authLogin: true },
    },
    {
        path: "shouhuodizhi",
        name: "AdminshouhuodizhiList",
        component: () => import("@/views/shouhuodizhi/list"),
        meta: { title: "收货地址列表", authLogin: true },
    },
    {
        path: "shouhuodizhi_tianjiaren",
        name: "AdminshouhuodizhiListtianjiaren",
        component: () => import("@/views/shouhuodizhi/list-tianjiaren"),
        meta: { title: "收货地址列表", authLogin: true },
    },
    {
        path: "shouhuodizhiadd",
        name: "AdminshouhuodizhiAdd",
        component: () => import("@/views/shouhuodizhi/add"),
        meta: { title: "添加收货地址", authLogin: true },
    },
    {
        path: "shouhuodizhiupdt",
        name: "AdminshouhuodizhiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shouhuodizhi/updt"),
        meta: { title: "编辑收货地址", authLogin: true },
    },
    {
        path: "shouhuodizhidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshouhuodizhiDetail",
        component: () => import("@/views/shouhuodizhi/detail"),
        meta: { title: "收货地址详情", authLogin: true },
    },
    {
        path: "fahuo",
        name: "AdminfahuoList",
        component: () => import("@/views/fahuo/list"),
        meta: { title: "发货列表", authLogin: true },
    },
    {
        path: "fahuo_xiadanren",
        name: "AdminfahuoListxiadanren",
        component: () => import("@/views/fahuo/list-xiadanren"),
        meta: { title: "发货列表", authLogin: true },
    },
    {
        path: "fahuoadd",
        name: "AdminfahuoAdd",
        component: () => import("@/views/fahuo/add"),
        meta: { title: "添加发货", authLogin: true },
    },
    {
        path: "fahuoupdt",
        name: "AdminfahuoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/fahuo/updt"),
        meta: { title: "编辑发货", authLogin: true },
    },
    {
        path: "fahuodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminfahuoDetail",
        component: () => import("@/views/fahuo/detail"),
        meta: { title: "发货详情", authLogin: true },
    },
    {
        path: "shouhuo",
        name: "AdminshouhuoList",
        component: () => import("@/views/shouhuo/list"),
        meta: { title: "收货列表", authLogin: true },
    },
    {
        path: "shouhuo_xiadanren",
        name: "AdminshouhuoListxiadanren",
        component: () => import("@/views/shouhuo/list-xiadanren"),
        meta: { title: "收货列表", authLogin: true },
    },
    {
        path: "shouhuoadd",
        name: "AdminshouhuoAdd",
        component: () => import("@/views/shouhuo/add"),
        meta: { title: "添加收货", authLogin: true },
    },
    {
        path: "shouhuoupdt",
        name: "AdminshouhuoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shouhuo/updt"),
        meta: { title: "编辑收货", authLogin: true },
    },
    {
        path: "shouhuodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshouhuoDetail",
        component: () => import("@/views/shouhuo/detail"),
        meta: { title: "收货详情", authLogin: true },
    },
    {
        path: "pinglun",
        name: "AdminpinglunList",
        component: () => import("@/views/pinglun/list"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglun_pinglunren",
        name: "AdminpinglunListpinglunren",
        component: () => import("@/views/pinglun/list-pinglunren"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglunupdt",
        name: "AdminpinglunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglun/updt"),
        meta: { title: "编辑评论", authLogin: true },
    },
];
