export default [
    {
        path: "xinwenxinxi",
        name: "IndexxinwenxinxiList",
        component: () => import("@/views/xinwenxinxi/index"),
        meta: { title: "新闻信息列表" },
    },
    {
        path: "xinwenxinxidetail",
        name: "IndexxinwenxinxiDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/xinwenxinxi/webdetail"),
        meta: { title: "新闻信息详情" },
    },
    {
        path: "liuyanbanadd",
        name: "IndexliuyanbanAdd",
        component: () => import("@/views/liuyanban/webadd"),
        meta: { title: "留言板添加", authLogin: true, msg: true },
    },
    {
        path: "shoucangadd",
        name: "IndexshoucangAdd",
        component: () => import("@/views/shoucang/webadd"),
        meta: { title: "收藏添加", authLogin: true, msg: true },
    },
    {
        path: "wxuseradd",
        name: "IndexwxuserAdd",
        component: () => import("@/views/wxuser/webadd"),
        meta: { title: "微信用户添加", authLogin: true, msg: true },
    },
    {
        path: "wxuserdetail",
        name: "IndexwxuserDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/wxuser/webdetail"),
        meta: { title: "微信用户详情" },
    },
    {
        path: "jiaju",
        name: "IndexjiajuList",
        component: () => import("@/views/jiaju/index"),
        meta: { title: "家具列表" },
    },
    {
        path: "jiajudetail",
        name: "IndexjiajuDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jiaju/webdetail"),
        meta: { title: "家具详情" },
    },
    {
        path: "gouwucheadd",
        name: "IndexgouwucheAdd",
        component: () => import("@/views/gouwuche/webadd"),
        meta: { title: "购物车添加", authLogin: true, msg: true },
    },
    {
        path: "dingdanadd",
        name: "IndexdingdanAdd",
        component: () => import("@/views/dingdan/webadd"),
        meta: { title: "订单添加", authLogin: true, msg: true },
    },
    {
        path: "dingdandetail",
        name: "IndexdingdanDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/dingdan/webdetail"),
        meta: { title: "订单详情", authLogin: true, msg: true },
    },
    {
        path: "shouhuodizhiadd",
        name: "IndexshouhuodizhiAdd",
        component: () => import("@/views/shouhuodizhi/webadd"),
        meta: { title: "收货地址添加", authLogin: true, msg: true },
    },
    {
        path: "fahuodetail",
        name: "IndexfahuoDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/fahuo/webdetail"),
        meta: { title: "发货详情", authLogin: true, msg: true },
    },
    {
        path: "shouhuoadd",
        name: "IndexshouhuoAdd",
        component: () => import("@/views/shouhuo/webadd"),
        meta: { title: "收货添加", authLogin: true, msg: true },
    },
    {
        path: "shouhuodetail",
        name: "IndexshouhuoDetail",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shouhuo/webdetail"),
        meta: { title: "收货详情", authLogin: true, msg: true },
    },
    {
        path: "pinglunadd",
        name: "IndexpinglunAdd",
        component: () => import("@/views/pinglun/webadd"),
        meta: { title: "评论添加", authLogin: true, msg: true },
    },
];
